;s_2_321w

PARS	EQU	CLK2+PQDEF+S_DELAY
VIDS	EQU	VIDEO+V_DELAY

; setup for fast flush
FPXFER0	DC	EFPXFER0-FPXFER0-GENCNT
		DC	PARS+RGH+S1H+S2H+S3H+SWH
		DC	PARS+RGH+S1H+S2H+S3H+SWH
EFPXFER0

; end fast flush
FPXFER2	DC	EFPXFER2-FPXFER2-GENCNT
		DC	PARS+RGL+S1L+S2H+S3L+SWL
		DC	PARS+RGL+S1L+S2H+S3L+SWL
EFPXFER2

; fast serial shift
FSXFER	DC	EFSXFER-FSXFER-GENCNT
		DC	PARS+RGL+S1H+S2H+S3L+SWL
		DC	PARS+RGL+S1H+S2L+S3L+SWL
		DC	PARS+RGL+S1H+S2L+S3H+SWH
		DC	PARS+RGL+S1L+S2L+S3H+SWH
		DC	PARS+RGL+S1L+S2H+S3H+SWH
		DC	PARS+RGH+S1L+S2H+S3L+SWL
EFSXFER

SXFER0	DC	ESXFER0-SXFER0-GENCNT
		DC	PARS+RGH+S1L+S2H+S3L+SWL
		DC	PARS+RGL+S1L+S2H+S3L+SWL
		DC	VIDS+%1110100		
		DC	PARS+RGL+S1H+S2H+S3L+SWL
		DC	PARS+RGL+S1H+S2L+S3L+SWL
		DC	PARS+RGL+S1H+S2L+S3H+SWH
		DC	PARS+RGL+S1L+S2L+S3H+SWH
		DC	PARS+RGL+S1L+S2H+S3H+SWH
		DC	PARS+RGL+S1L+S2H+S3L+SWH
ESXFER0

SXFER1	DC	ESXFER1-SXFER1-GENCNT
		DC	PARS+RGL+S1H+S2H+S3L+SWH
		DC	PARS+RGL+S1H+S2L+S3L+SWH
		DC	PARS+RGL+S1H+S2L+S3H+SWH
		DC	PARS+RGL+S1L+S2L+S3H+SWH
		DC	PARS+RGL+S1L+S2H+S3H+SWH
		DC	PARS+RGL+S1L+S2H+S3L+SWH
ESXFER1

SXFER2	DC	ESXFER2-SXFER2-GENCNT
	INCLUDE "int_noise.asm"
		DC	PARS+RGL+S1L+S2H+S3L+SWL
	INCLUDE "int_signal.asm"
ESXFER2

SXFER2D	DC	ESXFER2D-SXFER2D-GENCNT
		DC	SXMIT                   ; Transmit A/D data to host
	INCLUDE "int_noise.asm"
		DC	PARS+RGL+S1L+S2H+S3L+SWL
	INCLUDE "int_signal.asm"
ESXFER2D
